name: Log Visitor Data

on:
  push:
    branches:
      - main

jobs:
  log-visitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch visitor data
      run: |
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/andreigue/andreigue.github.io/contents/_data/visitors.json \
             -o visitors.json

    - name: Log visitor data
      env:
        IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
      run: |
        VISITOR_DATA=$(curl https://ipinfo.io?token=${{ secrets.IPINFO_TOKEN }})
        jq ". + [${VISITOR_DATA}]" visitors.json > updated_visitors.json

    - name: Commit and push changes
      run: |
        COMMIT_MESSAGE="Update visitor data"
        UPDATED_CONTENT=$(base64 -w 0 updated_visitors.json)
        SHA=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/andreigue/andreigue.github.io/contents/_data/visitors.json | jq -r .sha)
        curl -X PUT -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/andreigue/andreigue.github.io/contents/_data/visitors.json \
             -d @- << EOF
        {
          "message": "${COMMIT_MESSAGE}",
          "content": "${UPDATED_CONTENT}",
          "sha": "${SHA}"
        }
        EOF
